(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#editor'),ctx=canvas.getContext('2d'),form=$('#boothForm'),copy=v=>structuredClone(v),uid=()=>crypto.randomUUID(),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let venues=[],venue,workspace={version:1,active:'demo',events:{demo:{name:'示例展会 · 2026',halls:{}}}},selected=null,tool='select',camera={x:0,z:0,scale:2},drag=null,space=false,db,saveTimer,previewTimer;
const history=new Map(),images=new Map();let saveSequence=0;
const currentEvent=()=>workspace.events[workspace.active],key=()=>venue.key,state=()=>currentEvent().halls[key()]||(currentEvent().halls[key()]={booths:[],background:null});
const stack=()=>{const k=workspace.active+'/'+key();if(!history.has(k))history.set(k,{undo:[],redo:[]});return history.get(k)};
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500)}
function before(){const h=stack();h.undo.push(copy(state()));if(h.undo.length>30)h.undo.shift();h.redo=[]}
function changed(){draw();panels();$('#saveState').textContent='有修改 · 正在保存';clearTimeout(saveTimer);saveTimer=setTimeout(save,300)}
async function save(){clearTimeout(saveTimer);if(!db){$('#saveState').textContent='未保存 · 请导出备份';return false}const seq=++saveSequence;try{await new Promise((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put(copy(workspace),'workspace');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});if(seq===saveSequence)$('#saveState').textContent='草稿已保存 · 本机';return true}catch(e){$('#saveState').textContent='保存失败 · 请导出备份';toast('浏览器存储不可用或空间不足，请导出 JSON 备份');return false}}
async function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('necc-booth-studio-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('drafts');req.onerror=()=>reject(req.error);req.onsuccess=()=>resolve(req.result)})}
function image(src){if(!src)return null;if(!images.has(src)){const img=new Image();images.set(src,img);img.onload=draw;img.onerror=()=>toast('图片无法读取，请重新上传参考图');img.src=src}return images.get(src)}
const G=window.EditorGeometry;
const corners=b=>G.outline(b);
let polyDraft=[],hoverPoint=null,vertexIndex=-1,guides=[],viewAngle=0;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
function inside(p,poly){let hit=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.z>p.z)!==(b.z>p.z)&&p.x<(b.x-a.x)*(p.z-a.z)/(b.z-a.z)+a.x)hit=!hit}return hit}
function cross(a,b,c){return(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x)}
function intersects(a,b,c,d){return cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0}
function overlap(a,b){return a.some(p=>inside(p,b))||b.some(p=>inside(p,a))||a.some((p,i)=>b.some((q,j)=>intersects(p,a[(i+1)%a.length],q,b[(j+1)%b.length])))}
function problems(b){const p=corners(b),issues=[];if(p.some(q=>!inside(q,venue.polygon))||p.some((q,i)=>venue.polygon.some((r,j)=>intersects(q,p[(i+1)%p.length],r,venue.polygon[(j+1)%venue.polygon.length]))))issues.push('展位超出馆内可布展地板');if(venue.walls.some(([a,c])=>inside(a,p)||inside(c,p)||p.some((q,i)=>intersects(q,p[(i+1)%p.length],a,c))))issues.push('展位与固定墙体冲突');if(venue.rooms.some(r=>overlap(p,r.poly)))issues.push('展位与固定卫生间冲突');if(state().booths.some(o=>o.id!==b.id&&overlap(p,corners(o))))issues.push('与其他展位重叠');return issues}
function toScreen(p){const x=p.x-camera.x,z=p.z-camera.z,c=Math.cos(viewAngle),s=Math.sin(viewAngle);return{x:(x*c-z*s)*camera.scale+canvas.clientWidth/2,y:(x*s+z*c)*camera.scale+canvas.clientHeight/2}}
function toWorld(e){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left-canvas.clientWidth/2)/camera.scale,z=(e.clientY-r.top-canvas.clientHeight/2)/camera.scale,c=Math.cos(viewAngle),s=Math.sin(viewAngle);return{x:x*c+z*s+camera.x,z:-x*s+z*c+camera.z}}
function fit(){const b=venue.bounds,c=Math.abs(Math.cos(viewAngle)),s=Math.abs(Math.sin(viewAngle));camera={x:b.x+b.w/2,z:b.z+b.h/2,scale:Math.min((canvas.clientWidth-70)/(b.w*c+b.h*s),(canvas.clientHeight-110)/(b.w*s+b.h*c))};draw()}
function polygon(points,fill,stroke,width=1){ctx.beginPath();points.forEach((p,i)=>{const q=toScreen(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.lineWidth=width;ctx.strokeStyle=stroke;ctx.stroke()}}
function draw(){if(!venue)return;const dpr=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const b=venue.bounds,base=image(venue.image),tl=toScreen({x:b.x,z:b.z});polygon(venue.polygon,'#f8fafb','#b5c9cd');if(base?.complete&&base.naturalWidth){const p=toScreen({x:b.x+b.w/2,z:b.z+b.h/2});ctx.save();ctx.translate(p.x,p.y);ctx.rotate(viewAngle);ctx.drawImage(base,-b.w*camera.scale/2,-b.h*camera.scale/2,b.w*camera.scale,b.h*camera.scale);ctx.restore()}else polygon(venue.polygon,'#f8fafb','#b5c9cd');
const bg=state().background;if(bg){const img=image(bg.src),p=toScreen(bg);if(img?.complete&&img.naturalWidth){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(bg.angle*Math.PI/180+viewAngle);ctx.globalAlpha=bg.opacity;ctx.drawImage(img,-bg.w*camera.scale/2,-bg.h*camera.scale/2,bg.w*camera.scale,bg.h*camera.scale);ctx.restore()}if(tool==='reference'&&!bg.locked)polygon(corners(bg),null,'#b98b3b',2)}
for(const b of state().booths){polygon(corners(b),b.id===selected?'#43bba3a0':'#6fc7b780',b.id===selected?'#087465':'#348c7d',b.id===selected?2:1);const p=toScreen(b),width=b.w*camera.scale;if(width>24){ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='#164f45';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 12px sans-serif';ctx.fillText(b.code,0,b.shortName?-7:0,Math.max(15,width-5));if(b.shortName){ctx.font='11px sans-serif';ctx.fillText(b.shortName,0,9,Math.max(15,width-5))}ctx.restore()}if(b.id===selected){const points=corners(b);if(G.type(b)==='polygon'){points.forEach((p,i)=>handle(p,i===vertexIndex?'#ba487e':'#167569'));points.forEach((p,i)=>handle({x:(p.x+points[(i+1)%points.length].x)/2,z:(p.z+points[(i+1)%points.length].z)/2},'#658b84',3))}else handle(G.type(b)==='circle'?{x:b.x+b.radius,z:b.z}:points[2])}}
if(drag?.rect)polygon(corners(drag.rect),'#62cab650','#167569',2);if(polyDraft.length){const points=hoverPoint?[...polyDraft,hoverPoint]:polyDraft;polygon(points,'#62cab630','#167569',2);polyDraft.forEach((p,i)=>handle(p,i===0?'#ba487e':'#167569',i===0?7:5));if(hoverPoint){const p=toScreen(hoverPoint);ctx.fillStyle='#234b43';ctx.font='12px sans-serif';ctx.fillText(dist(polyDraft.at(-1),hoverPoint).toFixed(2)+' m',p.x+12,p.y-12)}}drawGuides();}
function number(){let i=1;while(state().booths.some(b=>b.code==='A'+String(i).padStart(3,'0')))i++;return 'A'+String(i).padStart(3,'0')}
function select(id){selected=id;vertexIndex=-1;panels();draw()}
function panels(){if(!venue)return;const s=state(),b=s.booths.find(b=>b.id===selected);$('#empty').hidden=!!b;form.hidden=!b;if(b){for(const name of ['code','shortName','company','intro','contact','phone','email','x','z','w','h','angle'])form.elements[name].value=typeof b[name]==='number'?Math.round(b[name]*100)/100:b[name]||'';$('#area').textContent=(G.type(b)==='circle'?Math.PI*b.radius*b.radius:G.area(corners(b))).toFixed(1)+' ㎡';shapePanel(b);$('#validation').textContent=problems(b).join('；')}
$('#count').textContent=s.booths.length+' 个';$('#listCount').textContent=s.booths.length;$('#boothList').replaceChildren();for(const b of s.booths){const button=document.createElement('button'),name=document.createElement('span');button.type='button';button.append(document.createTextNode(b.code));name.textContent=b.shortName||'待填企业';button.append(name);button.classList.toggle('active',b.id===selected);button.onclick=()=>select(b.id);$('#boothList').append(button)}$('#undo').disabled=!stack().undo.length;$('#redo').disabled=!stack().redo.length;
const bg=s.background;$('#referencePanel').hidden=!bg;if(bg){$('#referenceName').textContent=bg.name;$('#opacity').value=bg.opacity*100;$('#opacityValue').textContent=Math.round(bg.opacity*100)+'%';$('#bgWidth').value=bg.w.toFixed(1);$('#bgAngle').value=bg.angle;$('#lockReference').textContent=bg.locked?'解锁底图':'锁定底图';$('#lockReference').setAttribute('aria-pressed',String(bg.locked));$('#bgWidth').disabled=bg.locked;$('#bgAngle').disabled=bg.locked}$('#hallTitle').textContent=venue.floor+' / '+venue.id+' 馆';}
function chooseHall(v){canvas.onpointercancel();polyDraft=[];hoverPoint=null;vertexIndex=-1;guides=[];$('#polygonActions').hidden=true;drag=null;venue=v;selected=null;state();document.querySelectorAll('[data-floor]').forEach(b=>b.classList.toggle('active',b.dataset.floor===v.floor));$('#halls').replaceChildren();for(const h of venues.filter(h=>h.floor===v.floor)){const b=document.createElement('button');b.textContent=h.id;b.classList.toggle('active',h.key===v.key);b.onclick=()=>chooseHall(h);$('#halls').append(b)}panels();fit()}
function setTool(t){if(polyDraft.length&&t!==tool){if(!confirm('取消尚未完成的多边形？已保存展位不受影响。'))return;polyDraft=[]}canvas.onpointercancel();tool=t;hoverPoint=null;guides=[];$('#polygonActions').hidden=t!=='polygon';draftPanel();document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===t);b.setAttribute('aria-pressed',String(b.dataset.tool===t))});canvas.style.cursor=['draw','circle','polygon'].includes(t)?'crosshair':t==='pan'?'grab':'default';$('#hint').textContent={draw:'拖动绘制矩形 · 对齐边缘和中心',circle:'按下确定圆心，拖动设置半径',polygon:'逐点点击 · 点起点或“完成”闭合 · Backspace撤回 · Esc取消',select:'拖动移动；多边形拖顶点、点边中点加点；圆形拖圆周控制点',pan:'拖动画布平移 · 滚轮缩放',reference:'解锁后拖动参考图；左侧修改尺寸和角度'}[t];draw()}
canvas.onpointerdown=e=>{if(!venue||e.isPrimary===false||e.button>1||drag)return;canvas.focus();canvas.setPointerCapture(e.pointerId);const raw=toWorld(e);if(tool==='pan'||space||e.button===1){drag={kind:'pan',point:raw,camera:{...camera},pointer:e.pointerId};return}if(tool==='reference'){const bg=state().background;if(!bg||bg.locked){toast('请先添加并解锁参考图');return}before();drag={kind:'reference',point:raw,original:copy(bg),pointer:e.pointerId};return}if(tool==='polygon'){if(polyDraft.length>=3&&dist(raw,polyDraft[0])*camera.scale<12){finishPolygon();return}const p=snapped(raw,e,polyDraft.at(-1));if(polyDraft.length&&dist(p,polyDraft.at(-1))<.05)return;if(polyDraft.length>=256){toast('最多256个顶点');return}polyDraft.push(p);hoverPoint=null;draftPanel();draw();return}if(['draw','circle'].includes(tool)){const p=snapped(raw,e);drag={kind:tool,point:p,rect:{shape:tool==='circle'?'circle':'rect',x:p.x,z:p.z,w:0,h:0,radius:0,angle:0},pointer:e.pointerId};return}const chosen=state().booths.find(b=>b.id===selected);if(chosen){const points=corners(chosen);if(G.type(chosen)==='polygon'){const index=points.findIndex(p=>dist(p,raw)*camera.scale<12);if(index>=0){before();vertexIndex=index;drag={kind:'vertex',original:copy(chosen),points:copy(points),pointer:e.pointerId};shapePanel(chosen);return}const edge=points.findIndex((p,i)=>dist({x:(p.x+points[(i+1)%points.length].x)/2,z:(p.z+points[(i+1)%points.length].z)/2},raw)*camera.scale<9);if(edge>=0){const p=points[edge],q=points[(edge+1)%points.length];points.splice(edge+1,0,{x:(p.x+q.x)/2,z:(p.z+q.z)/2});if(!G.error(points)){before();Object.assign(chosen,G.fromWorld(points));vertexIndex=edge+1;changed()}return}}else{const q=G.type(chosen)==='circle'?{x:chosen.x+chosen.radius,z:chosen.z}:points[2];if(dist(q,raw)*camera.scale<15){before();drag={kind:G.type(chosen)==='circle'?'radius':'resize',original:copy(chosen),point:raw,pointer:e.pointerId};return}}}const hit=[...state().booths].reverse().find(b=>inside(raw,corners(b)));select(hit?.id||null);if(hit){before();drag={kind:'move',point:raw,original:copy(hit),pointer:e.pointerId}}};
canvas.onpointermove=e=>{const raw=toWorld(e);if(!drag){if(tool==='polygon'){hoverPoint=snapped(raw,e,polyDraft.at(-1));draw()}return}if(drag.pointer!==e.pointerId)return;const b=state().booths.find(b=>b.id===selected);let p=raw;if(drag.kind==='pan'){camera.x+=drag.point.x-p.x;camera.z+=drag.point.z-p.z}else if(drag.kind==='draw'){p=snapped(raw,e,drag.point);drag.rect={shape:'rect',x:(p.x+drag.point.x)/2,z:(p.z+drag.point.z)/2,w:Math.abs(p.x-drag.point.x),h:Math.abs(p.z-drag.point.z),angle:0};$('#hint').textContent=drag.rect.w.toFixed(2)+' × '+drag.rect.h.toFixed(2)+' 米'}else if(drag.kind==='circle'){p=snapped(raw,e);const r=dist(p,drag.point);drag.rect={shape:'circle',x:drag.point.x,z:drag.point.z,radius:r,w:r*2,h:r*2,angle:0};$('#hint').textContent='直径 '+(2*r).toFixed(2)+' 米'}else if(drag.kind==='reference'){state().background.x=drag.original.x+p.x-drag.point.x;state().background.z=drag.original.z+p.z-drag.point.z}else if(b&&drag.kind==='move'){const o=drag.original,center={x:o.x+p.x-drag.point.x,z:o.z+p.z-drag.point.z},a=G.anchors(o);p=snapped(center,e,null,{x:a.x.slice(0,3).map(x=>x-o.x),z:a.z.slice(0,3).map(z=>z-o.z)});b.x=p.x;b.z=p.z}else if(b&&drag.kind==='vertex'){p=snapped(raw,e);const points=copy(drag.points);points[vertexIndex]=p;drag.invalid=G.error(points);if(!drag.invalid)Object.assign(b,G.fromWorld(points));$('#hint').textContent=drag.invalid||'顶点 '+(vertexIndex+1)+' · '+p.x.toFixed(2)+', '+p.z.toFixed(2)+' 米'}else if(b&&drag.kind==='radius'){p=snapped(raw,e);b.radius=Math.max(.25,dist(p,b));b.w=b.h=b.radius*2}else if(b&&drag.kind==='resize'){p=snapped(raw,e);const o=drag.original,anchor=corners(o)[0],a=o.angle*Math.PI/180,c=Math.cos(a),s=Math.sin(a),dx=p.x-anchor.x,dz=p.z-anchor.z;b.w=Math.max(.5,dx*c+dz*s);b.h=Math.max(.5,-dx*s+dz*c);b.x=anchor.x+(b.w*c-b.h*s)/2;b.z=anchor.z+(b.w*s+b.h*c)/2}draw()};
canvas.onpointerup=e=>{if(!drag||e&&drag.pointer!==e.pointerId)return;const kind=drag.kind;if(['draw','circle'].includes(kind)&&drag.rect.w>=.5&&drag.rect.h>=.5){before();addBooth(drag.rect)}if(drag.invalid){const b=state().booths.find(b=>b.id===selected);if(b)Object.assign(b,drag.original);toast(drag.invalid+'，已恢复原形状')}drag=null;guides=[];if(kind!=='pan')changed();else draw()};
canvas.onpointercancel=()=>{if(!venue)return;if(drag&&['move','resize','reference','vertex','radius'].includes(drag.kind)){const prior=stack().undo.pop();if(prior)currentEvent().halls[key()]=prior}drag=null;guides=[];panels();draw()};
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=toWorld(e);camera.scale=clamp(camera.scale*Math.exp(-e.deltaY*.001),.15,80);const q=toWorld(e);camera.x+=p.x-q.x;camera.z+=p.z-q.z;draw()},{passive:false});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>chooseHall(venues.find(v=>v.floor===b.dataset.floor)));
$('#fit').onclick=fit;$('#zoomIn').onclick=()=>{camera.scale=clamp(camera.scale*1.3,.15,80);draw()};$('#zoomOut').onclick=()=>{camera.scale=clamp(camera.scale/1.3,.15,80);draw()};
function undo(redo=false){const h=stack(),from=redo?h.redo:h.undo,to=redo?h.undo:h.redo;if(!from.length)return;to.push(copy(state()));currentEvent().halls[key()]=from.pop();selected=null;changed()}
$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);$('#save').onclick=()=>save();
form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;const b=state().booths.find(b=>b.id===selected);if(!b)return;const values=Object.fromEntries(new FormData(form));values.code=values.code.trim();if(!values.code||state().booths.some(o=>o.id!==b.id&&o.code===values.code)){toast('请输入不重复的展位号');form.elements.code.focus();return}for(const k of ['x','z','w','h','angle']){values[k]=Number(values[k]??b[k]);if(!Number.isFinite(values[k])||Math.abs(values[k])>10000){toast('请输入合理的尺寸和坐标');return}}if(G.type(b)==='circle'){const d=Number(values.diameter);if(!Number.isFinite(d)||d<.5||d>400){toast('直径需在0.5～400米之间');return}values.radius=d/2;values.w=values.h=d;values.angle=0}else if(G.type(b)==='polygon')values.points=b.points.map(p=>({x:p.x*values.w/b.w,z:p.z*values.h/b.h}));delete values.diameter;const candidate={...b,...values},error=G.valid(candidate);if(error){toast(error);return}before();Object.assign(b,values);changed();toast('展位信息已更新')};
form.addEventListener('change',e=>{if(e.target.closest('#vertexTools'))return;form.requestSubmit()});
function removeBooth(){if(!selected)return;before();state().booths=state().booths.filter(b=>b.id!==selected);selected=null;changed();toast('展位已删除，可撤销恢复')}
$('#deleteBooth').onclick=removeBooth;$('#duplicate').onclick=()=>{const b=state().booths.find(b=>b.id===selected);if(!b)return;before();const n={...copy(b),id:uid(),code:number(),x:b.x+b.w+1};state().booths.push(n);selected=n.id;changed()};
addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('#previewDialog').open)return;if(e.code==='Space'){e.preventDefault();space=true}if(tool==='polygon'){if(e.key==='Enter'){e.preventDefault();finishPolygon();return}if(e.key==='Backspace'||e.key==='Delete'||(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();polyDraft.pop();draftPanel();draw();return}if(e.key==='Escape'){polyDraft=[];hoverPoint=null;draftPanel();draw();return}}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey)}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();if(vertexIndex>=0)deleteVertex();else removeBooth()}if(e.key==='Escape'){canvas.onpointercancel();selected=null;vertexIndex=-1;setTool('select');panels()}});addEventListener('keyup',e=>{if(e.code==='Space')space=false});addEventListener('blur',()=>{space=false;canvas.onpointercancel()});
$('#referenceFile').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>10*1024*1024){toast('请选择 10 MB 内的 JPG、PNG 或 WebP 图片');return}const target=state();try{const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)}),img=new Image();img.src=src;await img.decode();if(target!==state()){toast('展馆已切换，请在当前馆重新上传');return}if(target.background&&!confirm('替换当前参考图？已有展位不受影响，可撤销。'))return;before();const b=venue.bounds;target.background={src,name:f.name,x:b.x+b.w/2,z:b.z+b.h/2,w:b.w,h:b.w*img.height/img.width,angle:0,opacity:.45,locked:false};changed();setTool('reference');toast('拖动对齐底图，左侧调整尺寸后锁定')}catch(e){toast('图片读取失败，请重新选择')}};
$('#opacity').onchange=()=>{if(!state().background)return;before();state().background.opacity=Number($('#opacity').value)/100;changed()};$('#opacity').oninput=()=>$('#opacityValue').textContent=$('#opacity').value+'%';
$('#bgWidth').onchange=()=>{const bg=state().background,w=Number($('#bgWidth').value);if(!bg||bg.locked||!Number.isFinite(w)||w<1||w>2000){panels();return}before();bg.h*=w/bg.w;bg.w=w;changed()};$('#bgAngle').onchange=()=>{const bg=state().background,a=Number($('#bgAngle').value);if(!bg||bg.locked||!Number.isFinite(a))return;before();bg.angle=a%360;changed()};$('#lockReference').onclick=()=>{before();state().background.locked=!state().background.locked;if(state().background.locked)setTool('select');changed()};$('#deleteReference').onclick=()=>{before();state().background=null;changed();toast('参考图已删除，展位保留；可撤销')};
function events(){const el=$('#event');el.replaceChildren();for(const [id,event] of Object.entries(workspace.events)){const o=document.createElement('option');o.value=id;o.textContent=event.name;el.append(o)}el.value=workspace.active}
$('#event').onchange=()=>{workspace.active=$('#event').value;chooseHall(venue);changed()};$('#newEvent').onclick=()=>{const name=prompt('新展会名称');if(!name?.trim())return;const id=uid();workspace.events[id]={name:name.trim().slice(0,80),halls:{}};workspace.active=id;events();chooseHall(venue);changed()};
$('#export').onclick=()=>{const payload={version:2,units:'meters',event:currentEvent()},url=URL.createObjectURL(new Blob([JSON.stringify(payload)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='NECC-展位草稿-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#import').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>100*1024*1024)throw Error('文件过大');const v=JSON.parse(await f.text());if(![1,2].includes(v.version)||!v.event||typeof v.event.name!=='string'||!v.event.halls)throw Error('格式不匹配');const clean={name:v.event.name.slice(0,80)+'（导入）',halls:{}};for(const [k,s] of Object.entries(v.event.halls)){if(!venues.some(v=>v.key===k)||!Array.isArray(s.booths)||s.booths.length>5000)throw Error('馆号或展位数量不合法');const ids=new Set(),codes=new Set();for(const b of s.booths){if(['x','z','w','h','angle'].some(n=>!Number.isFinite(b[n])||Math.abs(b[n])>10000)||b.w<(G.type(b)==='polygon'?.05:.5)||b.h<(G.type(b)==='polygon'?.05:.5)||typeof b.id!=='string'||typeof b.code!=='string'||!b.code.trim()||ids.has(b.id)||codes.has(b.code))throw Error('展位数据无效或编号重复');const shapeError=G.valid(b);if(shapeError)throw Error(shapeError);ids.add(b.id);codes.add(b.code);for(const n of ['company','shortName','intro','contact','phone','email'])if(b[n]!=null&&typeof b[n]!=='string')throw Error('企业信息格式错误')}const bg=s.background;if(bg&&(!/^data:image\/(png|jpeg|webp);base64,/.test(bg.src)||['x','z','w','h','angle','opacity'].some(n=>!Number.isFinite(bg[n]))||bg.w<=0||bg.h<=0||bg.opacity<0||bg.opacity>1))throw Error('参考图格式错误');clean.halls[k]=s}const id=uid();workspace.events[id]=clean;workspace.active=id;events();chooseHall(venue);changed();toast('已导入为新展会，原有草稿未覆盖')}catch(e){toast('导入失败：'+e.message)}};
$('#preview').onclick=async()=>{const booths=copy(state().booths),hallKey=key(),issues=booths.filter(b=>problems(b).length).length;if(issues&&!confirm(`${issues} 个展位有越界或重叠提示，仍查看草稿预览？`))return;await save();$('#previewDialog').showModal();$('#previewStatus').hidden=false;$('#previewStatus').textContent='正在加载固定场馆…';const frame=$('#previewFrame');frame.src='./campus-all.html?view='+venue.floor+'&editorPreview=1';const began=Date.now();clearInterval(previewTimer);previewTimer=setInterval(()=>{if(!$('#previewDialog').open){clearInterval(previewTimer);return}if(Date.now()-began>30000){clearInterval(previewTimer);$('#previewStatus').textContent='加载超时，请检查网络后关闭重试';return}const win=frame.contentWindow,d=win?.venueDiagnostics;if(!d)return;clearInterval(previewTimer);const T=win.THREE,hall=d.halls.find(h=>h.floor+':'+h.id===hallKey);const style=win.document.createElement('style');style.textContent='.navigation-panel,.map-header,.floor-card,.legend-card,.booth-detail,.navigation-marker,.hall-label,.booth-label{display:none!important}.map-shell{grid-template-rows:1fr!important}.map-stage{height:100vh!important}';win.document.head.append(style);d.scene.traverse(o=>{if(o.userData.booth)o.visible=false});const group=new T.Group();for(const b of booths){const mesh=new T.Mesh(previewGeometry(T,b),new T.MeshStandardMaterial({color:0x6fc7b7,roughness:.78}));mesh.position.set(b.x,0,b.z);mesh.rotation.y=-b.angle*Math.PI/180;mesh.userData.editorBooth=b.id;mesh.userData.shape=G.type(b);group.add(mesh);const label=document.createElement('canvas');label.width=512;label.height=192;const c=label.getContext('2d');c.fillStyle='#143e38';c.textAlign='center';c.font='bold 55px sans-serif';c.fillText(b.code,256,74,490);c.font='44px sans-serif';c.fillText(b.shortName||'待填企业',256,146,490);const texture=new T.CanvasTexture(label),text=new T.Mesh(new T.PlaneGeometry(b.w*.85,Math.min(b.h*.85,b.w*.32)),new T.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}));text.rotation.x=-Math.PI/2;text.rotation.z=-b.angle*Math.PI/180;text.position.set(b.x,1.34,b.z);group.add(text)}hall.detailGroup.add(group);d.setView(hall.floor);d.focus(hall);d.zoom(Math.max(90,Math.max(hall.bounds.max.x-hall.bounds.min.x,hall.bounds.max.z-hall.bounds.min.z)*1.1));win.dispatchEvent(new Event('resize'));d.render();$('#previewStatus').textContent=`${hall.id} 馆 · ${booths.length} 个草稿展位 · 未发布`;setTimeout(()=>$('#previewStatus').hidden=true,4000)},150)};
function closePreview(){clearInterval(previewTimer);$('#previewDialog').close();$('#previewFrame').src='about:blank'}$('#closePreview').onclick=closePreview;$('#previewDialog').addEventListener('cancel',e=>{e.preventDefault();closePreview()});

function handle(p,color='#167569',radius=6){const q=toScreen(p);ctx.beginPath();ctx.arc(q.x,q.y,radius,0,Math.PI*2);ctx.fillStyle='white';ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke()}
function snapped(p,e={},anchor=null,offsets){guides=[];if(e.shiftKey&&anchor){const dx=p.x-anchor.x,dz=p.z-anchor.z,a=Math.round(Math.atan2(dz,dx)/(Math.PI/4))*Math.PI/4,r=Math.hypot(dx,dz);return{x:anchor.x+Math.cos(a)*r,z:anchor.z+Math.sin(a)*r}}if(e.altKey)return p;const result=G.snap(p,state().booths,{exclude:tool==='select'?selected:null,tolerance:Math.min(1,8/camera.scale),enabled:$('#snapEnabled').checked,grid:$('#snapGrid').checked,offsets});if($('#showGuides').checked)guides=result.guides;return result.point}
function drawGuides(){if(!$('#showGuides').checked)return;ctx.save();ctx.strokeStyle='#ba487e';ctx.lineWidth=1;ctx.setLineDash([5,4]);for(const g of guides){const a=toScreen(g.axis==='x'?{x:g.value,z:-20000}:{x:-20000,z:g.value}),b=toScreen(g.axis==='x'?{x:g.value,z:20000}:{x:20000,z:g.value});ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.restore()}
function addBooth(geometry){const b={...geometry,id:uid(),code:number(),company:'',shortName:'',intro:'',contact:'',phone:'',email:''};state().booths.push(b);selected=b.id;vertexIndex=-1}
function draftPanel(){$('#pointCount').textContent=polyDraft.length+' 个顶点';$('#finishPolygon').disabled=polyDraft.length<3;$('#backPoint').disabled=!polyDraft.length}
function finishPolygon(){const error=G.error(polyDraft);if(error){toast(error);return}before();addBooth(G.fromWorld(polyDraft));polyDraft=[];hoverPoint=null;setTool('select');changed()}
function shapePanel(b){const type=G.type(b);$('#shapeType').textContent={rect:'矩形',polygon:'多边形',circle:'圆形'}[type];$('#radiusField').hidden=type!=='circle';form.elements.diameter.disabled=type!=='circle';if(type==='circle')form.elements.diameter.value=(b.radius*2).toFixed(2);for(const n of ['w','h','angle']){form.elements[n].disabled=type==='circle';form.elements[n].closest('label').hidden=type==='circle'}$('#vertexTools').hidden=type!=='polygon';form.elements.w.min=form.elements.h.min=type==='polygon'?.05:.5;if(type==='polygon'){const points=corners(b),list=$('#vertexSelect');list.replaceChildren();for(let i=0;i<points.length;i++){const o=document.createElement('option');o.value=i;o.textContent='顶点 '+(i+1);list.append(o)}if(vertexIndex>=points.length)vertexIndex=-1;list.value=String(vertexIndex);$('#vertexX').value=vertexIndex>=0?points[vertexIndex].x.toFixed(2):'';$('#vertexZ').value=vertexIndex>=0?points[vertexIndex].z.toFixed(2):'';$('#deleteVertex').disabled=vertexIndex<0||points.length<=3;$('#applyVertex').disabled=vertexIndex<0}}
function deleteVertex(){const b=state().booths.find(b=>b.id===selected);if(!b||G.type(b)!=='polygon'||vertexIndex<0)return;const points=corners(b);points.splice(vertexIndex,1);const error=G.error(points);if(error){toast(error);return}before();Object.assign(b,G.fromWorld(points));vertexIndex=-1;changed()}
$('#finishPolygon').onclick=finishPolygon;$('#backPoint').onclick=()=>{polyDraft.pop();draftPanel();draw()};$('#cancelPolygon').onclick=()=>{polyDraft=[];hoverPoint=null;setTool('select')};$('#deleteVertex').onclick=deleteVertex;
$('#vertexSelect').onchange=()=>{vertexIndex=Number($('#vertexSelect').value);const b=state().booths.find(b=>b.id===selected);shapePanel(b);draw()};
$('#applyVertex').onclick=()=>{const b=state().booths.find(b=>b.id===selected);if(!b||vertexIndex<0)return;const points=corners(b);points[vertexIndex]={x:Number($('#vertexX').value),z:Number($('#vertexZ').value)};const error=G.error(points);if(error){toast(error);return}before();Object.assign(b,G.fromWorld(points));changed()};
for(const id of ['showGuides','snapEnabled','snapGrid'])$('#'+id).onchange=()=>{guides=[];draw()};
function previewGeometry(T,b){if(G.type(b)==='circle'){const geometry=new T.CylinderGeometry(b.radius,b.radius,1.3,128);geometry.translate(0,.65,0);return geometry}const points=G.local(b),shape=new T.Shape();points.forEach((p,i)=>i?shape.lineTo(p.x,-p.z):shape.moveTo(p.x,-p.z));shape.closePath();const geometry=new T.ExtrudeGeometry(shape,{depth:1.3,bevelEnabled:false,steps:1});geometry.rotateX(-Math.PI/2);return geometry}

window.installSVGImport({getVenue:()=>venue,getEvent:currentEvent,getBooths:()=>copy(state().booths),cancelGesture:()=>{canvas.onpointercancel()},commit:(rows,mode)=>{before();const booths=state().booths;for(const row of rows){const old=booths.find(b=>b.code===row.code);if(old){if(mode==='update'){delete old.points;delete old.radius;Object.assign(old,row)}}else booths.push({...row,id:uid(),company:'',shortName:'',intro:'',contact:'',phone:'',email:''})}selected=null;vertexIndex=-1;polyDraft=[];setTool('select');changed();toast('已导入 '+rows.length+' 个展位，可继续手动画图；撤销可恢复导入前草稿')}});
const viewTools=document.createElement('div');viewTools.className='drawing-options';viewTools.innerHTML='<strong>画布方向</strong><button id="horizontalView">横向铺满</button><button id="rotateView">旋转90°</button><button id="resetView">总图方向</button><span>仅调整观看方向，不改变展位坐标；展位自身旋转在右侧属性中调整。</span>';$('.toolbar').after(viewTools);$('#horizontalView').onclick=()=>{canvas.onpointercancel();viewAngle=venue.bounds.h>venue.bounds.w?-Math.PI/2:0;fit()};$('#rotateView').onclick=()=>{canvas.onpointercancel();viewAngle=(viewAngle+Math.PI/2)%(Math.PI*2);fit()};$('#resetView').onclick=()=>{canvas.onpointercancel();viewAngle=0;fit()};
window.installExcelExchange({venue:()=>venue,event:currentEvent,eventId:()=>workspace.active,booths:()=>copy(state().booths),toast,commit:updates=>{before();for(const update of updates){const b=state().booths.find(b=>b.id===update.id);if(b)Object.assign(b,update)}changed();toast('已更新 '+updates.length+' 个展位信息，可撤销')}});
new ResizeObserver(()=>draw()).observe($('#canvasWrap'));
(async()=>{try{const response=await fetch('./assets/editor/venues.json');if(!response.ok)throw Error('底图读取失败');venues=await response.json();try{db=await openDB();const saved=await new Promise((resolve,reject)=>{const req=db.transaction('drafts').objectStore('drafts').get('workspace');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});if(saved?.version===1)workspace=saved}catch(e){toast('本地存储不可用，本次修改请导出备份')}events();chooseHall(venues[0]);$('#saveState').textContent=db?'本机草稿 · 就绪':'未保存 · 请导出备份';window.boothEditorDiagnostics={get state(){return copy(state())},get venue(){return venue},get camera(){return {...camera,viewAngle}},get guides(){return copy(guides)},get draft(){return copy(polyDraft)},get selected(){return selected},toScreen,problems};}catch(e){$('#saveState').textContent='加载失败';toast(e.message+'，请通过 HTTP 地址打开并刷新')}})();
})();
