/* Browser-side information exchange. Geometry and fixed venue layers are never imported. */
(()=>{'use strict';
const headers=['楼层','场馆','展位ID','展位号','企业全称','企业简称','展位简介','联系人','联系电话','电子邮箱','形状（只读）','面积（㎡，只读）'];
const fields=['company','shortName','intro','contact','phone','email'],limits=[100,6,1000,40,40,100];
let library;
function load(){if(window.ExcelJS)return Promise.resolve();if(!library)library=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='./assets/vendor/exceljs-4.4.0.min.js';s.onload=resolve;s.onerror=()=>{library=null;s.remove();reject(Error('Excel组件加载失败，请刷新重试'))};document.head.append(s)});return library}
function plain(cell){const v=cell.value;if(v==null)return '';if(typeof v==='object'){if(v.formula||v.sharedFormula)throw Error('请将公式粘贴为数值/文本后再上传');if(v.richText)return v.richText.map(r=>r.text).join('');if(v.text!=null)return String(v.text);throw Error('单元格含日期或错误类型，请改为文本')}return String(v).trim()}
function zipLimit(buffer){const v=new DataView(buffer);let total=0,entries=0;for(let i=0;i+46<v.byteLength;i++){if(v.getUint32(i,true)!==0x02014b50)continue;total+=v.getUint32(i+24,true);entries++;if(total>32*1024*1024||entries>2000)throw Error('工作簿解压后过大，请只保留展位信息');i+=45+v.getUint16(i+28,true)+v.getUint16(i+30,true)+v.getUint16(i+32,true)}if(!entries)throw Error('请选择.xlsx工作簿，不支持旧.xls或加密文件')}
window.installExcelExchange=function(api){
 const section=document.createElement('section');section.innerHTML='<h2>Excel 信息维护</h2><button id="exportBoothExcel" class="wide">导出本馆 Excel</button><button id="openBoothExcel" class="wide bottom">上传编辑后的 Excel</button><p class="muted">批量改企业信息及展位号；几何轮廓保持不变。</p>';document.querySelector('aside.left').append(section);
 const dialog=document.createElement('dialog');dialog.id='excelDialog';dialog.setAttribute('aria-labelledby','excelTitle');dialog.innerHTML='<div class="svg-heading"><h2 id="excelTitle">Excel 信息回传</h2><button id="closeExcel">关闭</button></div><div class="excel-body"><p id="excelTarget"></p><label>选择编辑后的文件<input id="excelFile" type="file" accept=".xlsx"></label><label class="svg-review"><input type="checkbox" id="excelClearBlanks">空白单元格清空已有企业信息（默认空白不改）</label><p>以展位ID匹配；不要修改楼层、场馆及ID。没有ID时，按当前馆的展位号匹配。新展位请先在画布创建。</p><p id="excelStatus" role="status">仅预览，不立即改动草稿。</p><ul id="excelErrors"></ul><div class="excel-table-wrap"><table><thead><tr><th>展位</th><th>修改内容</th></tr></thead><tbody id="excelChanges"></tbody></table></div></div><div class="svg-footer"><span>不删展位、不改位置及轮廓，可撤销。</span><button id="applyExcel" class="primary" disabled>确认更新</button></div>';document.body.append(dialog);const $=id=>dialog.querySelector('#'+id);let target,book=null,changes=[],token=0,snapshot='';
 document.querySelector('#exportBoothExcel').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const hall=api.venue(),booths=api.booths();if(!booths.length)throw Error('请先绘制或导入展位');await load();const wb=new ExcelJS.Workbook(),sheet=wb.addWorksheet('展位信息',{views:[{state:'frozen',xSplit:4,ySplit:1,showGridLines:false}]});sheet.addRow(headers);for(const b of booths)sheet.addRow([hall.floor,hall.id,b.id,b.code,...fields.map(k=>b[k]||''),{rect:'矩形',circle:'圆形',polygon:'多边形'}[EditorGeometry.type(b)],Number((EditorGeometry.type(b)==='circle'?Math.PI*b.radius*b.radius:EditorGeometry.area(EditorGeometry.outline(b))).toFixed(2))]);
 const widths=[9,9,39,15,30,18,65,18,22,32,18,21];sheet.columns.forEach((c,i)=>{c.width=widths[i];if(i<11)c.numFmt='@'});sheet.getRow(1).height=30;sheet.getRow(1).eachCell(c=>{c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF233C45'}};c.font={name:'Arial',size:11,bold:true,color:{argb:'FFFFFFFF'}};c.alignment={vertical:'middle',horizontal:'center'}});for(let i=2;i<=sheet.rowCount;i++){const row=sheet.getRow(i);row.height=32;row.eachCell((c,j)=>{c.font={name:'Arial',size:11,color:{argb:j>=4&&j<=10?'FF233C45':'FF60757C'}};c.alignment={vertical:'middle',wrapText:true};if(j>=4&&j<=10)c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFF5DD'}}});}sheet.autoFilter={from:'A1',to:'L'+sheet.rowCount};sheet.getColumn(12).numFmt='0.00';
 const guide=wb.addWorksheet('回传说明');guide.columns=[{width:22},{width:105}];guide.addRows([['展会',api.event().name],['展会标识',api.eventId()],['目标馆',hall.key],['格式版本','NECC-BOOTH-INFO-1'],['可编辑列','淡黄色列：展位号、企业全称、企业简称（最多6字）、展位简介、联系人、联系电话、电子邮箱。'],['匹配方式','保持展位ID不变。排序、筛选后仍按ID匹配，不按行号匹配。'],['其他内容','不修改位置与形状，不删除未回传的展位，不创建新展位。'],['空白与公式','默认空白不改；如需清空信息，在回传窗口勾选。公式请先粘贴为值；电话保持文本。'],['回传流程','保存为.xlsx → 在同一展会与馆上传 → 检查变更预览 → 确认更新。']]);guide.eachRow(r=>{r.height=32;r.eachCell(c=>{c.font={name:'Arial',size:11};c.alignment={wrapText:true,vertical:'middle'}})});
 const buffer=await wb.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download=hall.floor+'-'+hall.id+'-展位信息.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);api.toast('已导出本馆Excel，黄色列可编辑');}catch(e){api.toast(e.message)}finally{button.disabled=false}};
 function close(){token++;book=null;changes=[];dialog.close()}
 document.querySelector('#openBoothExcel').onclick=()=>{target={venue:api.venue(),event:api.event()};snapshot=JSON.stringify(api.booths());book=null;changes=[];$('excelFile').value='';$('excelChanges').replaceChildren();$('excelErrors').replaceChildren();$('applyExcel').disabled=true;$('excelClearBlanks').checked=false;$('excelStatus').textContent='仅预览，不立即改动草稿。';$('excelTarget').textContent=target.event.name+' · '+target.venue.floor+' / '+target.venue.id+'馆';dialog.showModal()};$('closeExcel').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.addEventListener('keydown',e=>e.stopPropagation());
 $('excelFile').onchange=async()=>{const file=$('excelFile').files[0],seq=++token;book=null;changes=[];$('applyExcel').disabled=true;$('excelChanges').replaceChildren();$('excelErrors').replaceChildren();if(!file)return;$('excelStatus').textContent='正在读取工作簿…';try{if(!/\.xlsx$/i.test(file.name)||file.size>8*1024*1024)throw Error('请选择8MB以内的.xlsx文件');const buffer=await file.arrayBuffer();zipLimit(buffer);await load();const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer,{ignoreNodes:['drawing','picture','extLst']});if(seq!==token)return;book=wb;review()}catch(e){if(seq===token)$('excelStatus').textContent='无法读取：'+e.message}};
 function review(){changes=[];$('excelChanges').replaceChildren();$('excelErrors').replaceChildren();$('applyExcel').disabled=true;if(!book)return;const errors=[],booths=api.booths(),seen=new Set();try{const guide=book.getWorksheet('回传说明');if(guide&&(plain(guide.getCell('B2'))!==api.eventId()||plain(guide.getCell('B3'))!==target.venue.key))throw Error('文件来自其他展会或馆，请切换到对应工作台后上传');const sheet=book.getWorksheet('展位信息');if(!sheet)throw Error('找不到“展位信息”工作表，请使用导出的模板');if(sheet.rowCount>5001)throw Error('单馆最多5000条信息');for(let i=0;i<10;i++)if(plain(sheet.getRow(1).getCell(i+1))!==headers[i])throw Error('表头发生变化，请保留模板前10列名称及顺序');
 for(let i=2;i<=sheet.rowCount;i++){const row=sheet.getRow(i);if(!row.hasValues)continue;try{const values=Array.from({length:10},(_,j)=>plain(row.getCell(j+1)));if(values.every(v=>!v))continue;if(values[0]!==target.venue.floor||values[1]!==target.venue.id)throw Error('楼层/场馆不匹配');const old=values[2]?booths.find(b=>b.id===values[2]):booths.find(b=>b.code===values[3]);if(!old)throw Error('找不到对应展位，请保留ID或先在画布创建');if(seen.has(old.id))throw Error('同一展位重复出现');seen.add(old.id);const code=values[3];if(!code||code.length>24)throw Error('展位号需为1～24个字符');const update={id:old.id,code},details=[];if(code!==old.code)details.push('展位号：'+old.code+' → '+code);fields.forEach((key,j)=>{const value=values[j+4];if([...value].length>limits[j])throw Error(headers[j+4]+'超过'+limits[j]+'字');if(value||$('excelClearBlanks').checked){update[key]=value;if(value!==(old[key]||''))details.push(headers[j+4]+'：'+(old[key]||'空')+' → '+(value||'空'))}});if(details.length)changes.push({update,details,code:old.code});}catch(e){errors.push('第'+i+'行：'+e.message)}}
 const final=booths.map(b=>({id:b.id,code:changes.find(c=>c.update.id===b.id)?.update.code||b.code})),codes=new Set();for(const b of final){if(codes.has(b.code))errors.push('更新后展位号重复：'+b.code);codes.add(b.code)}
 }catch(e){errors.push(e.message)}for(const message of errors){const li=document.createElement('li');li.textContent=message;$('excelErrors').append(li)}for(const c of changes.slice(0,200)){const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td');a.textContent=c.code;b.textContent=c.details.join('；');tr.append(a,b);$('excelChanges').append(tr)}$('excelStatus').textContent=errors.length?`有 ${errors.length} 个问题，请修正后重新上传；本次未应用任何修改。`:`将更新 ${changes.length} 个展位；预览最多显示前200个。`;$('applyExcel').disabled=!!errors.length||!changes.length;
 }
 $('excelClearBlanks').onchange=review;$('applyExcel').onclick=()=>{if($('applyExcel').disabled)return;if(target.event!==api.event()||target.venue.key!==api.venue().key||snapshot!==JSON.stringify(api.booths())){$('excelStatus').textContent='草稿已变化，请关闭后重新上传，避免覆盖新修改。';$('applyExcel').disabled=true;return}api.commit(changes.map(c=>c.update));close()};
};
})();
